### PR TITLE
refactor: updated add to use node module lodash and not a local lodash file.

### PR DESCRIPTION
**Pull request by eaglejs**
- [x] Ready for review
- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?
Uses npm module of lodash

#### Where should the reviewer start?
testing the application and ensure that lodash is still working in deps.ts and logical.ts

#### How should this be manually tested?
testing the application and ensure that lodash is still working in deps.ts and logical.ts

#### Any background context you want to provide?
Simple fix, removed the lodash file, and added the node module for lodash.

#### What are the relevant tickets?
#55 Use `lodash` as a dep directly

#### Screenshots
n/a

#### Additional questions
n/a

### CODE REVIEW

**Comment by lili2311** [comment]
👋 @eaglejs Thank you for this contribution, this looks great but to release it we will need to have the commits updated to follow semantic release, please could you:
- squash into 1 commit
- use `feat: use npm module lodash instead of local one` as a commit message

**Comment by eaglejs** [comment]
Sure thing, i'll finish this up for ya.

**Comment by eaglejs** [comment]
Ok, I think I have it fixed now.

**Comment by lili2311** [comment]
@eaglejs please could you fo `git commit --amend` and change the commit message to start with `feat: npm module lodash directly.` It must have `feat:` in it to get released. 
Then you can push it with `git push -f` and we can merge!

**Comment by eaglejs** [comment]
Sure thing, i'm not on my development machine, i'll get on it in the morning.

**Comment by eaglejs** [comment]
Done.

**Comment by FauxFaux** [comment]
This was fixed as #56.

**Pull request closed without merging**
