### PR TITLE
chore: travis to build from node 10

### PR DESCRIPTION
**Pull request by aviadhahami**
- [X] Ready for review

#### What does this PR do?
Set Travis to build from node 10

### CODE REVIEW

**Review by dkontorovskyy — DISMISSED** [review]
Commit should be fix, not chore :)

**Comment by darscan** [comment]
@dkontorovskyy Definitely not a `fix` - this is purely build configuration

**Comment by dkontorovskyy** [comment]
@darscan chore is not releaseable commit prefix, isn't it? And this change blocks semantic release from happening

**Comment by darscan** [comment]
@dkontorovskyy We don't want this commit mentioned in release notes. It is not useful by itself. Semantic-release will still do the right thing (release all commits since the last release)

**Comment by aviadhahami** [comment]
So... any decision? :D

**Review by dkontorovskyy — APPROVED** [review]
LGTM

**Pull request merged**
